### ISSUE TITLE
Is there a way to perform pitch shifting while keeping multiple audios as synchronized as possible?

### ISSUE THREAD

**Issue by Ema38** [cutterbl/SoundTouchJS#15]
Thank you for making pitch shifting so easy.

Is there a way to apply pitch-shifting effects to multiple pieces of audio while keeping the audio as synchronized as possible?  

I'm trying to perform pitch shifting on multiple audios at once, while manipulating the gain of each audio.  
The following is a demo.  
[CodeSandBox](https://codesandbox.io/s/dazzling-cloud-kvj23?fontsize=14&hidenavigation=1&theme=dark)

The above demo is basically fine, but on mobile devices or low-spec devices, there may be a delay in the playback of individual audio.  
Also, moving ```input type=range``` will cause the above phenomenon to occur occasionally.

I was taught the following on Stack Overflow how to play multiple audios as synchronously as possible.  
```javascript
audioBufferSourceNode.start(ctx.currentTime)
```
[javascript - Is there any way to change the gain individually in real time when playing a node that is a composite of two AudioBuffers? - Stack Overflow](https://stackoverflow.com/questions/65919632/is-there-any-way-to-change-the-gain-individually-in-real-time-when-playing-a-nod/65922959?noredirect=1#comment116588218_65922959)

However, I know that shifterNode does not have a start method.  
So, if you have another solution, I would like to know about it.

**Comment by cutterbl** [comment]
Unfortunately, that isn't possible at this time, because of "how" SoundTouchJS reads the AudioBuffer and not the actual InputStream. I explain this a little better in a [blog post](https://cutterscrossing.com/development/ecmascript/webaudioapi/soundtouchjs/audioworklets/2020/05/14/why-is-soundtouch-working-as-a-pseudo-node/). It's something I would love to fix, but just haven't had the time to do so.
